version: '3.7'

services:
    users:
        image: users:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./users
            dockerfile: Dockerfile
        env_file:
            - ./users/.env
        volumes:
          - ./users:/app
#       ports:
#         - 8000:8000

    gateway:
        image: gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./gateway
            dockerfile: Dockerfile
        env_file:
            - ./gateway/.env
        volumes:
          - ./gateway:/app
        depends_on:
          - users
        ports:
          - 8001:8000
