version: '3.7'

services:
    users:
        image: users:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./users
            dockerfile: Dockerfile
        env_file:
            - ./users/.env
        volumes:
          - ./users:/app
        ports:
          - 8000:8000
